apply plugin: 'com.android.library'

apply plugin: "kotlin-android"

apply plugin: "com.google.devtools.ksp"

android {
    compileSdk 37
    namespace 'io.github.a2kaido.barcode.reader.data'

    compileOptions {
        sourceCompatibility = 21
        targetCompatibility = 21
    }
}

dependencies {
    implementation project(":domain")

    implementation "androidx.appcompat:appcompat:1.7.0"

    // kotlin
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3"

    // room
    def room_version = "2.7.1"
    implementation "androidx.room:room-runtime:$room_version"
    ksp "androidx.room:room-compiler:$room_version"
    implementation "androidx.room:room-ktx:$room_version"
}
